parameters:
#    mariapage.example.class: maria\pageBundle\Example

services:
#    mariapage.example:
#        class: %mariapage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
